### ISSUE TITLE
tree shaking in next-generation bundlers

### ISSUE THREAD

**Issue by justingreenberg** [tlackemann/minimize-bundle-js-size#1]
nice article!

it's probably worth mentioning that next-generation build systems (like rollup and webpack v2) support a feature called tree-shaking that excludes unused exports from bundles and provides the same level of optimization with import destructuring (as opposed to separate module imports). the technique relies on the static nature of ES modules to detect unused exports.

cheers :)

**Comment by tlackemann** [comment]
Thanks!

I've been reading on next-gen build systems and think it's great this support is coming. For existing projects that don't use the "new shiny" yet, this is a great quick-win to save some undesired bloat in your front-end applications. In a real world example, I took a plugin our team wrote and by applying this simple recommendation was able to save 2.4MB uncompressed and 0.3MB compressed. Not bad for literally changing how you `import` modules!

Looking forward to using the "new shiny" however :)

Cheers

**Comment by justingreenberg** [comment]
absolutely :) have a great weekend
