### ISSUE TITLE
Can not start the script

### ISSUE THREAD

**Issue by Julian-B90** [tlackemann/minimize-bundle-js-size#2]
Hi i have found two errors.

The first is in the package.json on line 27. 
This comma you must remove.
` "dependencies": {
    "lodash": "^4.0.0"
  }`

and in the package.json it give not a npm start script.

**Comment by tlackemann** [comment]
You are indeed correct. I suppose the project was never meant to be run but more looked at as an example.

If you want to submit a quick PR I'd be happy to merge it otherwise I'll most likely tackle this later.

Thanks!

**Comment by tlackemann** [comment]
Just merged in #3 which should address the installation problem. The instructions are also updated to read `npm run build` instead of `npm start`

Thanks for reporting!
